version: "3.4"

services:
  streamus:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: node
    command: bash -c "npm install && npm start"
    environment:
      - ARANGO_HOST=http://arangodb:8529
      - ARANGO_DATABASE=streamUs
      - ARANGO_ROOT_PASSWORD=root123
    ports:
      - 3000:3000
    volumes:
      - $PWD/src:/var/app/StreamUs
    links:
      - arangodb

  arangodb:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: arangodb
    ports:
      - 8520:8529
    environment:
      - ARANGO_ROOT_PASSWORD=root123
      - ARANGO_DATABASE=streamUs
