version: "3.4"

services:
  streamus:
    build:
      context: .
      target: node
    command: bash -c "npm install && npm start"
    ports:
      - 3000:3000
    volumes:
      - $PWD/src:/var/app/StreamUs
  arangodb:
    build:
      context: .
      target: arangodb
    ports:
      - 8520:8529
    environment:
      - ARANGO_ROOT_PASSWORD=root123
      - ARANGO_DATABASE=streamUs
